# The URL the site will be built for
base_url = "https://www.shivkr6.xyz/"

title = "Homepage"
description = "shiv's website"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

minify_html = true


ignored_content = ["*/**/*.zk/*"]

taxonomies = [
      {name = "tags", render = true, feed = true}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

extra_syntaxes_and_themes = ["static/assets/highlighting/gruvbox/"]

highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
]


[extra]

# Name of favicon file in `static/` folder
favicon = "favicon.png"

archive_years = [
  "2021",
  "2022",
]

theme_color = "auto"
# Put all your custom variables here
author = "shivang"

show_author = false

show_tags = true

show_masto_social = false
masto_url = "julialang.social"
masto_username = "shivkr6"
show_site_attribution = true
site_attribution_link = "https://creativecommons.org/licenses/by-sa/4.0/"
site_attribution_title = "CC-BY-4.0"

# Path to profpic. Better store it in static/assets/
profpic = ""

show_profpic = true

# TODO: Add font css settings
# I want to be able to switch between JuliaMono and an OldSchoolFont collection

# "dark" or "light"
theme_variant = "light"

# Other sections not mentioned
# If path is not provided, it defaults to `content/<name>/_index.md`
# more_sections = [
#   { name = "contact" },
# ]

# number_to_show = 3

show_external_links = false

external_links = [
  { name="contact", description = "contact me", permalink = "/contact/" },
]
