name = "gruvbox-v"
description = "A minimalistic gruvbox theme for Zola"
license = "MIT"
homepage = "https://codeberg.org/uncomfyhalomacro/gruvbox-v"
# The minimum version of Zola required
min_version = "0.8.0"
# The theme author info: you!
[author]
name = "socvirnyl estela"
homepage = "https://codeberg.org/uncomfyhalomacro/gruvbox-v"
